# Generated by Django 4.2.2 on 2023-06-13 01:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=30)),
                ('entrenador', models.CharField(blank=True, max_length=100)),
                ('nro_tarjeta', models.CharField(default='0000000000000000', max_length=16, verbose_name='número de tarjeta')),
                ('fecha_exp', models.DateField(default=datetime.date(2024, 1, 2), verbose_name='Fecha de vencimiento')),
                ('nombre_titular', models.CharField(default='', max_length=255, verbose_name='Nombre del titular')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
