# Generated by Django 4.2.2 on 2023-06-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGYM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='año_expiracion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cvv',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='mes_expiracion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
