# Generated by Django 4.2.2 on 2023-06-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGYM', '0002_usuarios_año_expiracion_usuarios_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_exp',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nro_tarjeta',
            field=models.CharField(default='0000000000000000', max_length=16, verbose_name='Número de tarjeta'),
        ),
    ]
