# Generated by Django 4.2.2 on 2023-06-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGYM', '0005_usuarios_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='altura',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='peso',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
