# Generated by Django 4.2.2 on 2023-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGYM', '0004_remove_usuarios_activo_usuarios_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
