# Generated by Django 4.2.2 on 2023-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGYM', '0007_alter_usuarios_altura_alter_usuarios_imc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('nivel', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='altura',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='año_expiracion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='hora',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imc',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='mes_expiracion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nro_tarjeta',
            field=models.CharField(default='0000000000000000', max_length=16, null=True, verbose_name='Número de tarjeta'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='peso',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
    ]
