# Generated by Django 4.2.1 on 2023-05-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apelllido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=30)),
                ('entrenador', models.CharField(max_length=100)),
            ],
        ),
    ]
