# Generated by Django 4.2.1 on 2023-05-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoGym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='entrenador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
