# Generated by Django 4.2.1 on 2023-05-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoGym', '0002_alter_usuarios_entrenador_alter_usuarios_idusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='apelllido',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
