# Generated by Django 4.2.1 on 2023-06-10 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "proyectoGym",
            "0003_rename_apelllido_usuarios_apellido_usuarios_activo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="tarjeta",
        ),
        migrations.AddField(
            model_name="usuarios",
            name="fecha_exp",
            field=models.DateField(
                default=datetime.date(2024, 1, 2), verbose_name="Fecha de vencimiento"
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="nombre_titular",
            field=models.CharField(
                default="", max_length=255, verbose_name="Nombre del titular"
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="nro_tarjeta",
            field=models.CharField(
                default="0000000000000000",
                max_length=16,
                verbose_name="número de tarjeta",
            ),
        ),
    ]
