# Generated by Django 4.2.1 on 2023-06-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoGym', '0004_remove_usuarios_tarjeta_usuarios_fecha_exp_and_more'),
        ('proyectoGym', '0005_remove_usuarios_activo_remove_usuarios_contraseña_and_more'),
    ]

    operations = [
    ]
