# Generated by Django 4.2.1 on 2023-06-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoGym', '0006_merge_20230612_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
