# Generated by Django 4.2.1 on 2023-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoGym', '0007_usuarios_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default=' ', max_length=256),
        ),
    ]
