# Generated by Django 4.2.1 on 2023-06-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoGym', '0011_usuarios_cvv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_exp',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='año_expiracion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='mes_expiracion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
